---
- hosts: all
  gather_facts: no
  roles:
    - role: "avinetworks.avisdk"
  connection: local
  vars_files: ./vars.yml
  any_errors_fatal: true

  tasks:
    - name: Calling patch_upgrade role - LEADER
      include_role:
        name: patch_upgrade
      when:
        - image_type[0] == "IMAGE_TYPE_PATCH"
        - cluster_uuid == gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"

    - name: Calling system_upgrade role - LEADER
      include_role:
        name: system_upgrade
      when:
        - image_type[0] == "IMAGE_TYPE_SYSTEM"
        - cluster_uuid == gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"

    - name: Monitor Upgrade - LEADER
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: "upgradestatusinfo"
      register: upgrade_status
      until: "{{ upgrade_status | upgrade_result() }}"
      delay: 30
      retries: 80
      when: 
        - cluster_uuid == gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"

    - name: disable_gslb_maintenance_mode
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"       
        http_method: post
        timeout: 3000
        path: gslbsiteops/maintenancemode
        data:
          enabled: False
      when: cluster_uuid == gslb.obj.results.0.leader_cluster_uuid